### ISSUE TITLE
gcc version test pervasive when not needed

### ISSUE THREAD

**Issue by sbryngelson** [ComputationalFlowPhysics/MFC-develop#35]
This test runs even if one is not compiling with GCC and throws a warning flag (-dumpversion doesn't exist)

https://github.com/ComputationalFlowPhysics/MFC-develop/blob/383a0cfa0716c2dd0fa31f4854119f7e6dce53a0/Makefile.in#L56

Not sure if there is an easy workaround.

**Comment by henryleberre** [comment]
A hacky way to implement this would be to simply redirect that command's output to null.

**Comment by sbryngelson** [comment]
Whatever works.
